# Generated by Django 3.2.4 on 2021-09-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, null=True, verbose_name='Maximo Puntaje'),
        ),
    ]
