# Generated by Django 3.2.4 on 2021-09-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_alter_pregunta_max_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Puntaje Total'),
        ),
    ]
